# Generated by Django 5.0.4 on 2024-05-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_videocall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='username',
            new_name='uid',
        ),
    ]
